project_id = "aizgpxaqvtvvqarzjmze"

[functions.manage-user]
verify_jwt = true

[functions.submit-public-form]
verify_jwt = false

[functions.manage-resend-domain]
verify_jwt = true

[functions.send-bulk-email]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.webhook-receiver]
verify_jwt = false

[functions.queue-manager]
verify_jwt = true

[functions.analyze-lead]
verify_jwt = true

[functions.indiamart-webhook]
verify_jwt = false

[functions.sync-gupshup-templates]
verify_jwt = true

[functions.send-whatsapp-message]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.create-gupshup-template]
verify_jwt = true

[functions.bulk-whatsapp-sender]
verify_jwt = true

[functions.retry-failed-whatsapp]
verify_jwt = false

[functions.email-inbound-webhook]
verify_jwt = false

[functions.exotel-make-call]
verify_jwt = true

[functions.exotel-webhook]
verify_jwt = false

[functions.exotel-get-recording]
verify_jwt = true

[functions.exotel-sync-call-logs]
verify_jwt = true

[functions.bulk-import-trigger]
verify_jwt = true

[functions.process-bulk-import]
verify_jwt = false

[functions.rollback-bulk-import]
verify_jwt = true

[functions.crm-bridge-api]
verify_jwt = false

[functions.chat-campaign-assistant]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-subscription-email]
verify_jwt = true

[functions.google-calendar-oauth]
verify_jwt = true

[functions.automation-trigger-handler]
verify_jwt = false

[functions.automation-email-sender]
verify_jwt = false

[functions.email-tracking]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.blog-webhook]
verify_jwt = false
