project_id = "aizgpxaqvtvvqarzjmze"

[functions.submit-public-form]
verify_jwt = false

[functions.webhook-receiver]
verify_jwt = false

[functions.queue-manager]
verify_jwt = true

[functions.analyze-lead]
verify_jwt = true

[functions.indiamart-webhook]
verify_jwt = false

[functions.sync-gupshup-templates]
verify_jwt = true

[functions.send-whatsapp-message]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.create-gupshup-template]
verify_jwt = true

[functions.bulk-whatsapp-sender]
verify_jwt = true

[functions.retry-failed-whatsapp]
verify_jwt = false
