project_id = "aizgpxaqvtvvqarzjmze"

[functions.submit-public-form]
verify_jwt = false

[functions.queue-manager]
verify_jwt = true

[functions.analyze-lead]
verify_jwt = true

[functions.indiamart-webhook]
verify_jwt = false
